# Generated by Django 4.2.1 on 2023-09-05 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_bannerimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('jpgrasm', models.ImageField(upload_to='patent/img')),
                ('pdfrasm', models.FileField(upload_to='patent/pdf')),
            ],
        ),
    ]
